alias be='bundle exec'
alias code='cd $(ghq list -p | peco)'
alias l="gls -lAh --color"
alias la='gls -A --color'
alias ll="gls -l --color"
alias ls="gls -F --color"
alias lt='gls -lArht --color'
alias priceiswrong='afplay ~/.sounds/priceiswrong.mp3'
alias restartpow="touch ~/.pow/restart.txt"
alias rimshot='afplay ~/.sounds/rimshot.mp3'
