#!/bin/bash

failed_items=""
function install_package() {
echo EXECUTING: brew install $1 $2
brew install $1 $2
[ $? -ne 0 ] && $failed_items="$failed_items $1"  # package failed to install.
}
brew tap caskroom/cask
brew tap codekitchen/dinghy
brew tap homebrew/apache
brew tap homebrew/completions
brew tap homebrew/fuse
brew tap homebrew/games
brew tap homebrew/python
brew tap homebrew/science
brew tap homebrew/versions
brew tap homebrew/x11
brew tap michaeldfallen/formula
install_package akka ''
install_package aldo ''
install_package ansible ''
install_package ant ''
install_package apache-spark ''
install_package autoconf ''
install_package automake ''
install_package avro-tools ''
install_package bamtools ''
install_package berkeley-db ''
install_package boost ''
install_package brew-cask ''
install_package bwa ''
install_package cairo ''
install_package ccat ''
install_package cgal ''
install_package cmake ''
install_package coreutils ''
install_package cromwell ''
install_package curl ''
install_package czmq ''
install_package dhex ''
install_package diff-so-fancy ''
install_package dinghy ''
install_package dnsmasq ''
install_package dos2unix ''
install_package drake ''
install_package eigen ''
install_package elasticsearch ''
install_package elinks ''
install_package exiftool ''
install_package faac ''
install_package fastqc ''
install_package ffmpeg ''
install_package fftw ''
install_package figlet ''
install_package fontconfig '  --universal
  --universal
  --universal'
install_package freetype '  --universal
  --universal
  --universal'
install_package freexl ''
install_package gcc ''
install_package gd '  --universal
  --universal
  --universal'
install_package gdal ''
install_package gdbm ''
install_package gdk-pixbuf ''
install_package geos ''
install_package gettext ''
install_package giflib ''
install_package git ''
install_package git-lfs ''
install_package giter8 ''
install_package glib ''
install_package gmp ''
install_package gnu-tar ''
install_package gnutls ''
install_package go ''
install_package gobject-introspection ''
install_package gpac ''
install_package gperftools ''
install_package gpp ''
install_package graphicsmagick ''
install_package graphviz ''
install_package harfbuzz ''
install_package htop ''
install_package htslib ''
install_package httpie ''
install_package icu4c ''
install_package ilmbase ''
install_package imagemagick ''
install_package isl ''
install_package isl014 ''
install_package jasper '  --universal'
install_package jpeg '  --universal'
install_package jq ''
install_package json-c ''
install_package jsonnet ''
install_package jsonpp ''
install_package kibana ''
install_package lame ''
install_package libao ''
install_package libav ''
install_package libdbi ''
install_package libevent ''
install_package libexif ''
install_package libffi ''
install_package libgcrypt ''
install_package libgeotiff ''
install_package libgpg-error ''
install_package libgphoto2 '  --universal
  --universal'
install_package libgsf ''
install_package libicns '  --universal'
install_package liblwgeom ''
install_package libmpc ''
install_package libpng '  --universal
  --universal
  --universal
  --universal'
install_package libsodium ''
install_package libspatialite ''
install_package libtasn1 '  --universal'
install_package libtiff '  --universal
  --universal'
install_package libtool '  --universal'
install_package libusb '  --universal
  --universal'
install_package libusb-compat '  --universal'
install_package libvo-aacenc ''
install_package libxml2 ''
install_package libyaml ''
install_package little-cms2 '  --universal'
install_package lzlib ''
install_package makedepend ''
install_package maven ''
install_package mockserver ''
install_package mongodb ''
install_package mongoose ''
install_package mpfr ''
install_package mysql ''
install_package nettle ''
install_package nginx ''
install_package nifi ''
install_package node ''
install_package noti ''
install_package nq ''
install_package numpy ''
install_package oniguruma ''
install_package opencv ''
install_package openexr ''
install_package openjpeg ''
install_package openslide ''
install_package openssl '  --universal
  --universal
  --universal
  --universal
  --universal'
install_package orc ''
install_package pango ''
install_package pcre ''
install_package perl ''
install_package picard-tools ''
install_package pixman ''
install_package pkg-config ''
install_package plantuml ''
install_package postgis ''
install_package postgresql ''
install_package pow ''
install_package primesieve ''
install_package proj ''
install_package py2cairo ''
install_package py3cairo ''
install_package pyenv ''
install_package pyenv-virtualenv ''
install_package pygobject3 ''
install_package python ''
install_package python3 ''
install_package r ''
install_package rapidjson ''
install_package rbenv ''
install_package readline ''
install_package redis ''
install_package ruby-build ''
install_package s3cmd ''
install_package s3fs ''
install_package samtools ''
install_package sane-backends '  --universal'
install_package sbt ''
install_package scala ''
install_package sfcgal ''
install_package sl ''
install_package spark ''
install_package speedtest_cli ''
install_package sqlite ''
install_package sshfs ''
install_package stow ''
install_package subversion ''
install_package terminal-notifier ''
install_package the_silver_searcher ''
install_package tmux ''
install_package tomcat7 ''
install_package tree ''
install_package unfs3 ''
install_package vim ''
install_package vips ''
install_package watch ''
install_package watson ''
install_package wemux ''
install_package wget ''
install_package wifi-password ''
install_package wine ''
install_package x264 ''
install_package xvid ''
install_package xz ''
install_package yank ''
install_package youtube-dl ''
install_package zeromq ''
install_package zsh ''
[ ! -z $failed_items ] && echo The following items were failed to install: && echo $failed_items
